name: styling
description: All theme and styling specify files
publish_to: none

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  # for the platform check
  universal_platform: 1.0.0+1
  freezed_annotation: 2.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  flutter_lints: 3.0.1
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master



flutter:
